I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 299, in script
    Lead Moore "Absolute Cinema!"
Exception: Sayer 'Lead' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 299, in script
    Lead Moore "Absolute Cinema!"
  File "C:\Users\LENOVO\Desktop\Study related\Renpy\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\LENOVO\Desktop\Study related\Renpy\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\LENOVO\Desktop\Study related\Renpy\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Lead' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
Alchemi 1.0
Wed Mar 12 23:03:53 2025
